spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.140.187:3306/wechat?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456789
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
    service:
      name: order
    locator:
      discovery:
        enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 134.175.140.187
    port: 5672
    username: guest
    password: guest
  redis:
    host: 134.175.140.187
    port: 6379
  jpa:
    show-sql: true
    hibernate:
          ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
          #      naming:
          #        strategy: org.hibernate.cfg.ImprovedNamingStrategy
          #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8082

env:
  dev3

wangzhou:
  age: 1090011
  
# #变ribbon负载均衡的规则
# #PRODUCT:
#  # ribbon:
#   #   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRul
#变ribbon负载均衡的规则,默认是轮询
#PRODUCT:
#  ribbon:
#     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
            #下面的不设置就默认1000
    getProductInfoList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000


feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: debug
#management:
#  server:
#    servlet:
#      context-path: /
