spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.140.187:3306/wechat?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456789
  zipkin:
      base-url: http://zipkin:9411/
      service:
        name: product
  sleuth:
      sampler:
        probability: 1.0
  rabbitmq:
    host: 134.175.140.187
    port: 5672
    username: guest
    password: guest
  redis:
    host: 134.175.140.187
    port: 6379
  jpa:
    show-sql: true
    hibernate:
          ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
          #      naming:
          #        strategy: org.hibernate.cfg.ImprovedNamingStrategy
          #      #  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8084
