spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf8&useSSL=true&ENGINE=InnoD
    username: root
    password: 123456789
  rabbitmq:
    host: 134.175.140.187
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
    hibernate:
          ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
          #      naming:
          #        strategy: org.hibernate.cfg.ImprovedNamingStrategy
          #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8084
