spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.140.187:3306/wechat?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456789
 
  redis:
    host: 134.175.140.187
    port: 6379
  jpa:
    show-sql: true
    hibernate:
          ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
          #      naming:
          #        strategy: org.hibernate.cfg.ImprovedNamingStrategy
          #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8085

env:
  dev3

wangzhou:
  age: 10900
  
# #变ribbon负载均衡的规则
# #PRODUCT:
#  # ribbon:
#   #   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
